"""initial

Revision ID: 9a177488f213
Revises: 
Create Date: 2026-06-04 17:28:27.604994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a177488f213'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('acao', sa.Enum('PRODUTO_CRIADO', 'PRODUTO_ATUALIZADO', 'PEDIDO_CRIADO', 'MOVIMENTACAO_ESTOQUE', 'PEDIDO_CANCELADO', name='log_action'), nullable=False),
    sa.Column('detalhe', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_acao'), 'logs', ['acao'], unique=False)
    op.create_index(op.f('ix_logs_data_criacao'), 'logs', ['data_criacao'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CANCELADO', name='order_status'), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('preco > 0', name='ck_products_preco_positive'),
    sa.CheckConstraint('quantidade_estoque >= 0', name='ck_products_estoque_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False, comment='Preço no momento da compra — imutável após criação'),
    sa.CheckConstraint('preco_unitario > 0', name='ck_order_items_preco_positive'),
    sa.CheckConstraint('quantidade > 0', name='ck_order_items_quantidade_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_produto_id'), 'order_items', ['produto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_produto_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_index(op.f('ix_logs_data_criacao'), table_name='logs')
    op.drop_index(op.f('ix_logs_acao'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
